import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Brain, TrendingUp, AlertTriangle, Activity } from "lucide-react";
import { formatPercentage } from "@/utils/agentMetrics";

export default function Intelligence() {
  return (
    <div className="flex-1 space-y-6 p-8 pt-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between space-y-2">
        <h2 className="text-3xl font-bold tracking-tight font-display">Intelligence Core</h2>
      </div>
      
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card className="glass-card">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Market Sentiment</CardTitle>
            <Brain className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-success">Bullish</div>
            <p className="text-xs text-muted-foreground mt-1">
              Based on on-chain volume and Twitter sentiment.
            </p>
          </CardContent>
        </Card>

        <Card className="glass-card">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Top Opportunity</CardTitle>
            <TrendingUp className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary">JUP Arbitrage</div>
            <p className="text-xs text-muted-foreground mt-1">
              Expected yield: {formatPercentage(0.85)} (High Confidence)
            </p>
          </CardContent>
        </Card>

        <Card className="glass-card">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Risk Alerts</CardTitle>
            <AlertTriangle className="h-4 w-4 text-warning" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-warning">2 Active</div>
            <p className="text-xs text-muted-foreground mt-1">
              High volatility detected in meme coin pairs.
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-7">
        <Card className="glass-card col-span-4">
          <CardHeader>
            <CardTitle>AI Inference Stream</CardTitle>
            <CardDescription>Real-time deductions from the Neural Engine.</CardDescription>
          </CardHeader>
          <CardContent>
             <div className="space-y-4">
                {[
                  "Detected 14% volume spike in SOL/USDC pools on Orca.",
                  "Whale wallet (9xA...2P1) just unloaded 5M BONK.",
                  "Liquid staking yields increased by 0.5% across the board.",
                  "Network congestion is low, ideal time for complex routing."
                ].map((msg, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-lg border border-white/5 bg-white/5">
                    <Activity className="h-4 w-4 text-primary shrink-0" />
                    <span className="text-sm text-white/80">{msg}</span>
                  </div>
                ))}
             </div>
          </CardContent>
        </Card>

        <Card className="glass-card col-span-3">
          <CardHeader>
            <CardTitle>Yield Strategies</CardTitle>
            <CardDescription>Auto-generated by AI</CardDescription>
          </CardHeader>
          <CardContent>
             <div className="space-y-4">
                <div className="p-4 rounded-xl border border-white/10 bg-black/20">
                  <div className="flex justify-between items-start mb-2">
                    <div className="font-semibold text-primary">Delta Neutral SOL</div>
                    <div className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded uppercase font-bold tracking-widest">Active</div>
                  </div>
                  <p className="text-xs text-muted-foreground">Maintains exposure while farming Kamino vaults.</p>
                </div>
                <div className="p-4 rounded-xl border border-white/10 bg-black/20">
                  <div className="flex justify-between items-start mb-2">
                    <div className="font-semibold text-primary">Stablecoin Loop</div>
                    <div className="text-xs bg-white/10 text-white/50 px-2 py-0.5 rounded uppercase font-bold tracking-widest">Idle</div>
                  </div>
                  <p className="text-xs text-muted-foreground">Recursive borrowing on MarginFi for maximum APY.</p>
                </div>
             </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
